version: '3.8'

services:
  fastapi_app:
    build: ..
    container_name: fact_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
